// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxManagement.Infrastructure.Database;

#nullable disable

namespace TaxManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130074226_'InitialMigrations'")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxManagement.Domain.Entities.TaxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompetenceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("competence_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentAuthenticationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_authentication_code");

                    b.Property<DateTimeOffset?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaxRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_rule_id");

                    b.Property<decimal>("TotalOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_order_amount");

                    b.Property<decimal>("TotalOrderTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_order_tax");

                    b.HasKey("Id")
                        .HasName("pk_tax_entries");

                    b.HasIndex("CompetenceDate")
                        .HasDatabaseName("idx_taxentry_competencedate");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("idx_taxentry_orderid");

                    b.HasIndex("TaxRuleId")
                        .HasDatabaseName("ix_tax_entries_tax_rule_id");

                    b.ToTable("tax_entries", "core");
                });

            modelBuilder.Entity("TaxManagement.Domain.Entities.TaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("destination_state")
                        .IsFixedLength();

                    b.Property<decimal>("DifalRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("difal_rate");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_date");

                    b.Property<decimal>("FcpRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fcp_rate");

                    b.Property<decimal>("InterstateRate")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("interstate_rate");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("OriginState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("origin_state")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_tax_rules");

                    b.HasIndex("OriginState", "DestinationState", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("idx_taxrules_origin_dest_date");

                    b.ToTable("tax_rules", "core");
                });

            modelBuilder.Entity("TaxManagement.Domain.Entities.TaxEntry", b =>
                {
                    b.HasOne("TaxManagement.Domain.Entities.TaxRule", null)
                        .WithMany()
                        .HasForeignKey("TaxRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_taxentry_taxrule_taxruleid");
                });
#pragma warning restore 612, 618
        }
    }
}
